# Generated by Django 5.1 on 2024-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='appartment_type',
            field=models.CharField(choices=[('', 'appartment type'), ('Luxury', 'luxury'), ('semi-luxury', 'semi-luxury'), ('normal', 'normal')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appartment',
            name='estimated_price',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
