# Generated by Django 5.1 on 2024-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_updateda_at_appartment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appartment',
            name='appartment_type',
            field=models.CharField(choices=[('', 'appartment type'), ('Luxury', 'Luxury'), ('semi-luxury', 'Semi-luxury'), ('normal', 'Normal')], default='', max_length=100),
        ),
    ]
