# Generated by Django 3.2.12 on 2024-09-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_apartment_booking_delete_appartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name_plural': 'Manage Apartments'},
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(blank=True, choices=[('Luxury', 'Luxury'), ('Semi-luxury', 'Semi-luxury'), ('Normal', 'Normal')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
