# Generated by Django 3.2.12 on 2024-09-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240902_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
