# Generated by Django 3.2.12 on 2024-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20240902_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('PP', 'PayPal'), ('BT', 'Bank Transfer')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.CharField(blank=True, default='Address', max_length=255, null=True),
        ),
    ]
