# Generated by Django 3.2.12 on 2024-08-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
