# Generated by Django 3.2.12 on 2024-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_house_size_house_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='contact_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='house',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='house',
            name='map_url',
            field=models.URLField(default='http://maps.google.com/'),
        ),
    ]
