# Generated by Django 3.2.12 on 2024-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20240830_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='map_url',
            field=models.URLField(default='http://maps.google.com/', max_length=800),
        ),
    ]
