# Generated by Django 3.2.12 on 2024-08-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_house_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='map_url',
            field=models.CharField(default='http://maps.google.com/', max_length=800),
        ),
    ]
