# ci cd pipeline configurarion files/
name: Django CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build --file Dockerfile --tag my-django-app:latest .

    - name: Push Docker image
      run: |
        docker tag my-django-app:latest ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    - name: Deploy to Server
      run: |
        ssh user@yourserver "docker pull ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest && docker-compose up -d"
